export {default as Login} from './Login';
export {default as Courses} from './EnrolledCourses';
export {default as NewCourses} from './EmployeeCourses';
export {default as Course} from './Course';
export {default as CourseRequest} from './CourseRequest';
export {default as EditEmployee} from './EditEmployee';
export {default as TrainingAssignment} from './TrainingAssignment';
export {default as CreateLiveMeeting} from './CreateLiveMeeting'
export {default as ListEmployees} from './ListEmployees'
export {default as EmployeePerformance} from './EmployeePerformance'
export {default as Video} from './Video'
export {default as EditCourse} from './EditCourse'
export {default as Register} from './Register'
export {default as CreateCourse} from './CreateCourse';
export {default as UploadVideo} from './UploadVideo';
export {default as ListVideo} from './ListVideos';
export {default as EditVideo} from './EditVideo';
export {default as ListCourses} from './ListCourses';
export {default as ListCategories} from './ListCategories';
export {default as EditCategory} from './EditCategory';
export {default as CreateCategory} from './CreateCategory';